#!/bin/bash
sudo apt update
sudo apt install -y libncurses5 pigz rclone
mkdir -p /tmp/hi
cd /tmp/hi
curl -LO https://github.com/Apon77/binaries/raw/master/x86_64/ccache.tar.gz
tar xf ccache.tar.gz
sudo cp ccache /usr/bin/ccache
rm -rf /tmp/hi
